import feteDeLhuitre from "../assets/img/fete-de-lhuitre.jpg";
import auRayonDesMerveilles from "../assets/img/ardm.jpg";
import museeDeNantes from "../assets/img/midn.jpg";
import biome from "../assets/img/biome.mp4";
import manVsForest from "../assets/img/manvsforest.mp4";
import seigneurAnneaux from "../assets/img/sda.mp4";

export const realisationsList = [
  {
    titreDuProjet: "Fête de l'huître",
    texteRapide:
      "Réalisation d'une affiche et brochure pour la Fête de l'huître de Sainte Hélène",
    annee: "2018",
    client: "Fête de l'huître",
    theme: "Huître",
    categorie: "design graphique",
    imagePrincipale: feteDeLhuitre,
    explication: "explication",
    processus: "processus",
    enjeux: "enjeux",
    imagesSecondaires: "imagesSecondaires",
    id: "1",
  },
  {
    titreDuProjet: "Au rayon des merveilles",
    texteRapide:
      "Réalisation d'un logo et de la charte graphique pour un compte instagram de lecture",
    annee: "2021",
    client: "Au rayon des merveille",
    theme: "Livre",
    categorie: "design graphique",
    imagePrincipale: auRayonDesMerveilles,
    explication: "explication",
    processus: "processus",
    enjeux: "enjeux",
    imagesSecondaires: "imagesSecondaires",
    id: "2",
  },
  {
    titreDuProjet: "Musée de l'imprimerie de Nantes",
    texteRapide:
      "Réalisation d'une affiche pour le musée de l'imprimerie de Nantes",
    annee: "2018",
    client: "Musée de l'imprimerie de Nantes",
    theme: "Imprimerie",
    categorie: "design graphique",
    imagePrincipale: museeDeNantes,
    explication: "explication",
    processus: "processus",
    enjeux: "enjeux",
    imagesSecondaires: "imagesSecondaires",
    id: "3",
  },
  {
    titreDuProjet: "Biome",
    texteRapide: "Ce projet parle de ça",
    annee: "2019",
    client: "Biome",
    theme: "Maquillage",
    categorie: "motion design",
    imagePrincipale: biome,
    explication: "explication",
    processus: "processus",
    enjeux: "enjeux",
    imagesSecondaires: "imagesSecondaires",
    id: "4",
  },
  {
    titreDuProjet: "Man vs Forest",
    texteRapide: "Ce projet parle de ça",
    annee: "2019",
    client: "Man vs Forest",
    theme: "theme",
    categorie: "motion design",
    imagePrincipale: manVsForest,
    explication: "explication",
    processus: "processus",
    enjeux: "enjeux",
    imagesSecondaires: "imagesSecondaires",
    id: "5",
  },
  {
    titreDuProjet: "Le seigneur des anneaux",
    texteRapide: "Ce projet parle de ça",
    annee: "2018",
    client: "Le seigneur des anneaux",
    theme: "theme",
    categorie: "motion design",
    imagePrincipale: seigneurAnneaux,
    explication: "explication",
    processus: "processus",
    enjeux: "enjeux",
    imagesSecondaires: "imagesSecondaires",
    id: "6",
  },
  {
    titreDuProjet: "Projet web design 1",
    texteRapide: "Ce projet parle de ça",
    annee: "annee",
    client: "client",
    theme: "theme",
    categorie: "web design",
    imagePrincipale: "imagePrincipale",
    explication:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet ornare ligula. Vestibulum laoreet, nisl sit amet tempus consequat, tellus nunc rhoncus libero, non pharetra sapien sapien ut enim. Curabitur elementum non turpis elementum malesuada. Nulla interdum ipsum eget aliquam efficitur. Ut scelerisque lorem facilisis quam volutpat efficitur. Ut dignissim ac tellus quis fringilla. Suspendisse eu egestas urna. Nam sed nisi tellus. Suspendisse vel ligula diam. Vivamus ullamcorper libero vitae eros efficitur, in iaculis metus volutpat.",
    processus:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet ornare ligula. Vestibulum laoreet, nisl sit amet tempus consequat, tellus nunc rhoncus libero, non pharetra sapien sapien ut enim. Curabitur elementum non turpis elementum malesuada. Nulla interdum ipsum eget aliquam efficitur. Ut scelerisque lorem facilisis quam volutpat efficitur. Ut dignissim ac tellus quis fringilla. Suspendisse eu egestas urna. Nam sed nisi tellus. Suspendisse vel ligula diam.",
    enjeux:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse sit amet ornare ligula. Vestibulum laoreet, nisl sit amet tempus consequat, tellus nunc rhoncus libero, non pharetra sapien sapien ut enim. Curabitur elementum non turpis elementum malesuada. Nulla interdum ipsum eget aliquam efficitur. Ut scelerisque lorem facilisis quam volutpat efficitur. Ut dignissim ac tellus quis fringilla. Suspendisse.",
    imagesSecondaires: "imagesSecondaires",
    id: "7",
  },
  {
    titreDuProjet: "Projet web design 2",
    texteRapide: "Ce projet parle de ça",
    annee: "annee",
    client: "client",
    theme: "theme",
    categorie: "web design",
    imagePrincipale: "imagePrincipale",
    explication: "explication",
    processus: "processus",
    enjeux: "enjeux",
    imagesSecondaires: "imagesSecondaires",
    id: "8",
  },
  {
    titreDuProjet: "Projet web design 3",
    texteRapide: "Ce projet parle de ça",
    annee: "annee",
    client: "client",
    theme: "theme",
    categorie: "web design",
    imagePrincipale: "imagePrincipale",
    explication: "explication",
    processus: "processus",
    enjeux: "enjeux",
    imagesSecondaires: "imagesSecondaires",
    id: "9",
  },
  {
    titreDuProjet: "Projet web design 4",
    texteRapide: "Ce projet parle de ça",
    annee: "annee",
    client: "client",
    theme: "theme",
    categorie: "web design",
    imagePrincipale: "imagePrincipale",
    explication: "explication",
    processus: "processus",
    enjeux: "enjeux",
    imagesSecondaires: "imagesSecondaires",
    id: "10",
  },
];
